apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "otusk8s3.fullname" . }}-config
  labels:
    {{- include "otusk8s3.labels" . | nindent 4 }}
data:
  DB_HOST: {{ include "otusk8s3.fullname" . }}-postgresql
  DB_PORT: "5432"
  DB_USER: {{ .Values.postgresql.postgresqlUsername | quote }}
  DB_NAME: {{ .Values.postgresql.postgresqlDatabase | quote }}
