secrets:
    postgresql-postgres-password: ENC[AES256_GCM,data:KYzWZRIvWLad,iv:vPB+046111h1lDoceBWPqoAof92Eld7rc29xNmXDuLM=,tag:ceF58i+7a4tEMpOhA7Rk9Q==,type:str]
    postgresql-password: ENC[AES256_GCM,data:y+rGQ5Yx70Yt,iv:H6AI6pTxgbFZV8Qt2uDuSiSE3ZK1anIHP8S6jAHAJ5U=,tag:oppwRQZvu7+3sph2BDDVoA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-07-29T17:54:03Z"
    mac: ENC[AES256_GCM,data:UaaaEakjFEVpe3Jm/gRPqT9xN3jEwVabXwnGOMJKeK+FNBZkT0sdUi3wnzOhwQsx4+pg616PtzE87pFqYaVJtBuzgWRu+DOklxHyWK06uX/nGS1PL8VjocCiIsAHN7ZJeWMY3paYv9gha0ecH9DUqwv55WGVo9HWZiR50FFvQ4c=,iv:T0pZpI8ISbRAjvtugyy5B72z1SRd8wjcm01BmtpLKz0=,tag:BD0WMfU6ZdiL+NU4QcT9BA==,type:str]
    pgp:
        - created_at: "2021-07-29T17:54:02Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4D52i+39ZQTJcSAQdAJdMS0EXi9kBqeiXmTDXh97Zuyf4LbqIEkoE90y53pGAw
            PvT7HetaT3TjB0Lyp5M6bhPi3nJzMC1RgaBN/TGjxTT+an9EelSBPhUhtyCD+bND
            1GgBCQIV0U1aZzEKBGAC4OJIplW5aJejh7g8gb7tFPiJO2s0pZP/imzi0zAhyus7
            N3DxoxG8rtdPK1GBzChxnW4Ea3EZQM2LE0g4gKxGrHsjMXGDHGc7waZRPeqmHhvr
            ofkF+Rf3jeWh1A==
            =S1Ww
            -----END PGP MESSAGE-----
          fp: B6119512DF978E928359015628DDF8638AE4D1EE
    unencrypted_suffix: _unencrypted
    version: 3.7.1
